# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    nao.twig_extension:
            class: NaoBundle\Twig\NaoExtension
            public: false
            tags:
                - { name: twig.extension }

    nao.notification:
            class: NaoBundle\Services\Notification\Notification
            arguments:
                - "@mailer"
                - "@twig"
                - "@doctrine.orm.entity_manager"

    nao.send_contact_mail:
            class: NaoBundle\Services\ContactMail\ContactMail
            arguments:
                - "@mailer"
                - "@twig"
                - "@doctrine.orm.entity_manager"

    nao_bundle.password_resetting:
        class: NaoBundle\EventListener\PasswordResettingListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
    nao_bundle.profile_edit:
        class: NaoBundle\EventListener\ProfileEditListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
    nao_bundle.change_password:
        class: NaoBundle\EventListener\ChangePasswordListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }