# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    #service_name:
        #    class: AppBundle\Directory\ClassName
        #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    nao.twig_extension:
            class: NaoBundle\Twig\NaoExtension
            public: false
            tags:
                - { name: twig.extension }

    nao.notification:
            class: NaoBundle\Services\Notification\Notification
            arguments:
                - "@mailer"
                - "@twig"
                - "@doctrine.orm.entity_manager"

    nao.send_contact_mail:
            class: NaoBundle\Services\ContactMail\ContactMail
            arguments:
                - "@mailer"
                - "@twig"
                - "@doctrine.orm.entity_manager"

