# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    nao.twig_extension:
            class: NaoBundle\Twig\NaoExtension
            public: false
            tags:
                - { name: twig.extension }

    nao.notification:
            class: NaoBundle\Services\Notification\Notification
            arguments:
                - "@mailer"
                - "@twig"
                - "@doctrine.orm.entity_manager"

    nao.send_contact_mail:
            class: NaoBundle\Services\ContactMail\ContactMail
            arguments:
                - "@mailer"
                - "@twig"
                - "@doctrine.orm.entity_manager"

